/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/scene.gltf --transform 
Files: public/models/scene.gltf [546.67KB] > C:\Users\KIIT0001\my-3d-portfolio\scene-transformed.glb [1.49MB] (-173%)
Author: saadhesham626 (https://sketchfab.com/saadhesham626)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/programmer-desk-setup-stylized-3d-room-ede58cf414534e47b57bf788dc075b17
Title: Programmer Desk Setup – Stylized 3D Room
*/

import React, { useEffect } from 'react'
import { useGLTF, useAnimations, useTexture } from '@react-three/drei'

export function Model({ onMenuClick, ...props }) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/models/scene-transformed.glb')
  const { actions } = useAnimations(animations, group)

  const monitorTexture = useTexture('/spidey.jpg')
  // ADD THIS BLOCK RIGHT HERE:
  useEffect(() => {
    // This looks at every animation in the file and presses play!
    Object.values(actions).forEach((action) => {
      action.play();
    });
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null} onClick={(e) => {
      e.stopPropagation(); // Stops the click from registering objects behind it
      console.log("Clicked Mesh Name:", e.object.name);
      console.log("Clicked Material:", e.object.material.name);
    }}>
      <group name="Sketchfab_Scene">
        <group name="GLTF_SceneRootNode">
          <group name="Sphere_217" position={[2.538, 1.368, -2.949]} scale={0.381}>
            <mesh name="Object_369" geometry={nodes.Object_369.geometry} material={materials['SVGMat.017_15']} />
          </group>
          <group name="Empty009_313" position={[1.437, 1.734, -2.237]}>
            <group name="Cylinder013_308" position={[-0.142, -0.399, -0.053]} rotation={[-1.573, 0, Math.PI]} scale={[-0.036, 0.366, 0.037]}>
              <mesh name="Object_515" geometry={nodes.Object_515.geometry} material={materials.PaletteMaterial001} />
              <mesh name="Object_516" geometry={nodes.Object_516.geometry} material={materials.Base} />
            </group>
            <group name="Empty007_310" position={[-0.133, -0.425, 0.297]} rotation={[-Math.PI, 0, -0.805]} scale={[-0.281, 0.281, 0.281]}>
              <group name="Circle004_309" position={[-0.006, 0.022, 3.029]} rotation={[-Math.PI / 2, 1.22, -Math.PI]}>
                <mesh name="Object_521" geometry={nodes.Object_521.geometry} material={materials.PaletteMaterial001} />
              </group>
            </group>
            <group name="Empty008_312" position={[-0.133, -0.387, 0.311]} rotation={[-Math.PI, 0, -0.805]} scale={[-0.281, 0.281, 0.281]}>
              <group name="Circle003_311" position={[-0.006, 0.022, 0]} rotation={[Math.PI / 2, -1.072, 0]} scale={0.89}>
                <mesh name="Object_524" geometry={nodes.Object_524.geometry} material={materials.PaletteMaterial001} />
              </group>
            </group>
          </group>
          <group name="Robot_Origin_318" position={[0, 0.615, 0]} rotation={[-Math.PI / 2, 0, 3.078]} scale={0.569} />
          <group name="Mouth_320" position={[5.089, 3.273, 2.127]} rotation={[-Math.PI / 2, 0, 3.078]} />
          <group name="Wave_321" position={[0, 0, 1]} rotation={[-Math.PI / 2, 0, 3.078]} />
          <group name="Wave002_322" position={[0, 0, 0.427]} rotation={[-Math.PI / 2, 0, 3.078]} scale={[1, 1, 0.474]} />
          <group name="Wave001_323" position={[0, 0, 0.819]} rotation={[-Math.PI / 2, 0, 3.078]} scale={[1, 1, 0.834]} />
          <group name="Wave003_324" position={[0, 0, 0.05]} rotation={[-Math.PI / 2, 0, 3.078]} scale={[1, 1, 0.128]} />
          <group name="Ears_325" position={[5.071, 3.498, 2.413]} scale={0.569} />
        </group>
        <group name="Empty001_277" position={[-1.553, 3.687, 1.17]} rotation={[0, -0.592, -2.972]} scale={[-0.068, 0.068, 0.068]}>
          <group name="Cylinder009_276">
            <mesh name="Object_478" geometry={nodes.Object_478.geometry} material={materials.light} />
          </group>
        </group>
        <group name="Empty002_279" position={[-1.553, 3.345, 1.17]} rotation={[0, -0.592, -2.972]} scale={[-0.068, 0.068, 0.068]}>
          <group name="Cylinder007_278">
            <mesh name="Object_481" geometry={nodes.Object_481.geometry} material={materials.light} />
          </group>
        </group>
        <group name="Empty003_281" position={[-1.553, 2.984, 1.17]} rotation={[0, -0.592, -2.972]} scale={[-0.068, 0.068, 0.068]}>
          <group name="Cylinder008_280">
            <mesh name="Object_484" geometry={nodes.Object_484.geometry} material={materials.light} />
          </group>
        </group>
        <group name="Empty004_283" position={[-1.956, 3.087, 1.922]} rotation={[Math.PI / 2, 0, 0]} scale={[-0.073, 0.073, 0.073]}>
          <group name="Cylinder010_282">
            <mesh name="Object_487" geometry={nodes.Object_487.geometry} material={materials.light} />
          </group>
        </group>
        <group name="Empty005_285" position={[-1.764, 3.115, 1.62]} rotation={[Math.PI / 2, 0, 0]} scale={[-0.073, 0.073, 0.073]}>
          <group name="Cylinder011_284">
            <mesh name="Object_490" geometry={nodes.Object_490.geometry} material={materials.light} />
          </group>
        </group>
        <group name="Empty006_287" position={[-1.624, 3.082, 1.347]} rotation={[Math.PI / 2, 0, 0]} scale={[-0.073, 0.073, 0.073]}>
          <group name="Cylinder012_286">
            <mesh name="Object_493" geometry={nodes.Object_493.geometry} material={materials.light} />
          </group>
        </group>
        <group name="Empty012_292" position={[-2.093, 3.448, 1.703]} rotation={[3.133, -1.039, 1.859]} scale={[-0.102, 0.095, 0.097]}>
          <group name="Cylinder014_291">
            <mesh name="Object_504" geometry={nodes.Object_504.geometry} material={materials.light} />
          </group>
        </group>
        <group name="RootNode005_364" position={[5.098, 1.348, 2.59]} rotation={[Math.PI, 0.5, -Math.PI]} scale={0.007}>
          <group name="Robot_Origin001_363" position={[0, 0.615, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <group name="Ears001_338" position={[0, 0, 2.967]}>
              <group name="Ears_Black_Matt_0_337">
                <mesh name="Object_555" geometry={nodes.Object_555.geometry} material={materials.PaletteMaterial001} />
              </group>
            </group>
            <group name="Empty011_341" position={[0, -0.06, 2.786]}>
              <group name="Eyes001_340" position={[0, -0.431, 0.076]}>
                <group name="Eyes_Blue_Light_0_339">
                  <mesh name="Object_559" geometry={nodes.Object_559.geometry} material={materials.PaletteMaterial001} />
                </group>
              </group>
            </group>
            <group name="Hand_origin_344" position={[0.723, 0, 2.015]}>
              <group name="hANDS001_343" position={[-0.723, 0, -1.963]}>
                <group name="hANDS_White_Glossy_0_342">
                  <mesh name="Object_563" geometry={nodes.Object_563.geometry} material={materials.PaletteMaterial004} />
                </group>
              </group>
            </group>
            <group name="Hand_origin002_347" position={[-0.723, 0, 2.015]} rotation={[0, 0, -Math.PI]}>
              <group name="hANDS003_346" position={[-0.723, 0, -1.963]}>
                <group name="hANDS002_White_Glossy_0_345">
                  <mesh name="Object_567" geometry={nodes.Object_567.geometry} material={materials.PaletteMaterial004} />
                </group>
              </group>
            </group>
            <group name="Mouth001_349" position={[0, -0.504, 2.573]}>
              <group name="Mouth_Blue_Light_0_348">
                <mesh name="Object_570" geometry={nodes.Object_570.geometry} material={materials.PaletteMaterial001} />
              </group>
            </group>
            <group name="Wave004_355" position={[0, 0, 1]}>
              <group name="Wave_Blue_Light_0_354">
                <mesh name="Object_580" geometry={nodes.Object_580.geometry} material={materials.PaletteMaterial001} />
              </group>
            </group>
            <group name="Wave005_357" position={[0, 0, 0.427]} scale={[1, 1, 0.474]}>
              <group name="Wave002_Blue_Light_0_356">
                <mesh name="Object_583" geometry={nodes.Object_583.geometry} material={materials.PaletteMaterial001} />
              </group>
            </group>
            <group name="Wave006_359" position={[0, 0, 0.819]} scale={[1, 1, 0.834]}>
              <group name="Wave001_Blue_Light_0_358">
                <mesh name="Object_586" geometry={nodes.Object_586.geometry} material={materials.PaletteMaterial001} />
              </group>
            </group>
            <group name="Wave007_361" position={[0, 0, 0.05]} scale={[1, 1, 0.128]}>
              <group name="Wave003_Blue_Light_0_360">
                <mesh name="Object_589" geometry={nodes.Object_589.geometry} material={materials.PaletteMaterial001} />
              </group>
            </group>
            <group name="Robot001_353" position={[0, 0, 0.051]}>
              <group name="Robot_Black_Matt_0_350">
                <mesh name="Object_573" geometry={nodes.Object_573.geometry} material={materials.PaletteMaterial001} />
              </group>
              <group name="Robot_Blue_Light_0_351">
                <mesh name="Object_575" geometry={nodes.Object_575.geometry} material={materials.PaletteMaterial001} />
              </group>
              <group name="Robot_White_Glossy_0_352">
                <mesh name="Object_577" geometry={nodes.Object_577.geometry} material={materials.PaletteMaterial004} />
              </group>
            </group>
          </group>
        </group>
        <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials['SVGMat.017']} position={[3.448, 3.267, 2.526]} rotation={[1.882, 0, 0]} />
        <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.PaletteMaterial001} position={[0.354, 2.989, 2.592]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.Base} position={[1.463, 5.561, 3.36]} rotation={[Math.PI, 0, -Math.PI / 2]} scale={0.918} />
        <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials['SVGMat.017_0']} position={[1.463, 5.561, 3.36]} rotation={[Math.PI, 0, -Math.PI / 2]} scale={0.918} />
        <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.light} position={[-2.951, 7.591, -0.783]} rotation={[0, -Math.PI / 2, 0]} scale={[1, 1, 0.948]} />
        <mesh name="Object_169" geometry={nodes.Object_169.geometry} material={materials['SVGMat.017_2']} position={[-0.273, 2.734, 2.265]} rotation={[Math.PI, -0.002, Math.PI]} scale={0.139} />
        <mesh name="Object_171" geometry={nodes.Object_171.geometry} material={materials['SVGMat.017_3']} position={[-0.273, 2.734, 2.265]} rotation={[Math.PI, -0.002, Math.PI]} scale={0.139} />
        <mesh name="Object_179" geometry={nodes.Object_179.geometry} material={materials['SVGMat.017_4']} position={[1.471, 2.734, 2.261]} rotation={[Math.PI, -0.002, Math.PI]} scale={0.139} />
        <mesh name="Object_181" geometry={nodes.Object_181.geometry} material={materials['SVGMat.017_5']} position={[1.471, 2.734, 2.261]} rotation={[Math.PI, -0.002, Math.PI]} scale={0.139} />
        <mesh name="Object_190" geometry={nodes.Object_190.geometry} material={materials['SVGMat.017_6']} position={[1.122, 2.734, 2.262]} rotation={[Math.PI, -0.002, Math.PI]} scale={0.139} />
        <mesh name="Object_201" geometry={nodes.Object_201.geometry} material={materials['SVGMat.017_7']} position={[0.425, 2.734, 2.263]} rotation={[Math.PI, -0.002, Math.PI]} scale={0.139} />
        <mesh name="Object_203" geometry={nodes.Object_203.geometry} material={materials['SVGMat.017_8']} position={[0.425, 2.734, 2.263]} rotation={[Math.PI, -0.002, Math.PI]} scale={0.139} />
        <mesh name="Object_212" geometry={nodes.Object_212.geometry} material={materials['SVGMat.017_9']} position={[0.076, 2.734, 2.264]} rotation={[Math.PI, -0.002, Math.PI]} scale={0.139} />
        <mesh name="Object_221" geometry={nodes.Object_221.geometry} material={materials['SVGMat.017_10']} position={[0.773, 2.734, 2.263]} rotation={[Math.PI, -0.002, Math.PI]} scale={0.139} />
        <mesh name="Object_223" geometry={nodes.Object_223.geometry} material={materials['SVGMat.017_11']} position={[0.773, 2.734, 2.263]} rotation={[Math.PI, -0.002, Math.PI]} scale={0.139} />
        <mesh name="Object_234" geometry={nodes.Object_234.geometry} material={materials['SVGMat.017_12']} position={[2.71, 2.959, 1.856]} rotation={[-1.692, 0.001, -0.12]} scale={0.422} />
        <mesh name="Object_270" geometry={nodes.Object_270.geometry} material={materials['SVGMat.017_13']} position={[1.965, 3.005, 1.795]} rotation={[Math.PI, -1.106, Math.PI]} scale={0.145} />
        <mesh name="Object_288" geometry={nodes.Object_288.geometry} material={materials.PaletteMaterial002} position={[-1.523, 3.363, 1.115]} rotation={[-Math.PI, 0.485, -Math.PI]} scale={[0.185, 0.062, 0.023]} />
        <mesh name="Object_336" geometry={nodes.Object_336.geometry} material={materials['SVGMat.017_14']} position={[-2.725, 6.45, -0.855]} rotation={[2.906, -0.057, 1.555]} scale={[0.318, 0.359, 0.08]} />
        <mesh name="Object_402" geometry={nodes.Object_402.geometry} material={materials['SVGMat.017_16']} position={[-3.188, 4.871, -1.289]} rotation={[-Math.PI / 2, -0.424, 1.557]} scale={0.202} />
       
        <mesh position={[0.484, 3.999, 2.534]} rotation={[0, 0, 0]} scale={[-3.7, 1.53, 0.825]}><planeGeometry /><meshBasicMaterial map={monitorTexture} toneMapped={false} color="white" side={2} /></mesh>

        <mesh name="Object_433" geometry={nodes.Object_433.geometry} material={materials['SVGMat.017_17']} position={[3.088, 1.029, -0.233]} scale={1.186} />
        <mesh name="Object_435" geometry={nodes.Object_435.geometry} material={materials['SVGMat.017_18']} position={[0.854, 1.005, -0.326]} rotation={[0, Math.PI / 2, 0]} scale={[3.864, 2.502, 3.807]} />
        <mesh name="Object_446" geometry={nodes.Object_446.geometry} material={materials.PaletteMaterial003} position={[1.877, 1.214, 1.774]} rotation={[-1.475, 0.081, 2.543]} scale={3.526} />
        <mesh name="Object_510" geometry={nodes.Object_510.geometry} material={materials['SVGMat.017_19']} position={[-2.122, 2.233, -4.376]} rotation={[Math.PI, 0.976, -Math.PI]} scale={0.034} />
        <mesh name="Object_511" geometry={nodes.Object_511.geometry} material={materials.Material_63_0} position={[-2.122, 2.233, -4.376]} rotation={[Math.PI, 0.976, -Math.PI]} scale={0.034} />
        <mesh name="Object_512" geometry={nodes.Object_512.geometry} material={materials.Material_63_1} position={[-2.122, 2.233, -4.376]} rotation={[Math.PI, 0.976, -Math.PI]} scale={0.034} />
      </group>
      {/* HITBOX FOR 'ABOUT' */}
<mesh 
  position={[7.0, 6.6, 3.4]} // Changed -3.8 to a positive 3.8!
  onClick={(e) => { e.stopPropagation(); onMenuClick('ABOUT'); }}
  onPointerOver={() => document.body.style.cursor = 'pointer'}
  onPointerOut={() => document.body.style.cursor = 'auto'}
>
  <boxGeometry args={[2.8, 0.8, 1.0]} />
  <meshBasicMaterial color="#00ff00" transparent opacity={0} />
</mesh>
{/* HITBOX FOR 'SKILLS' */}
<mesh 
  position={[7.0, 5.25, 3.4]} // Lowered the Y number
  onClick={(e) => { e.stopPropagation(); onMenuClick('SKILLS'); }}
  onPointerOver={() => document.body.style.cursor = 'pointer'}
  onPointerOut={() => document.body.style.cursor = 'auto'}
>
  <boxGeometry args={[2.8, 0.8, 1.0]} />
  <meshBasicMaterial color="#00ff00" transparent opacity={0} />
</mesh>

{/* HITBOX FOR 'WORKS' */}
<mesh 
  position={[7.0, 3.9, 3.4]} // Lowered the Y number even more
  onClick={(e) => { e.stopPropagation(); onMenuClick('WORKS'); }}
  onPointerOver={() => document.body.style.cursor = 'pointer'}
  onPointerOut={() => document.body.style.cursor = 'auto'}
>
  <boxGeometry args={[2.8, 0.8, 1.0]} />
  <meshBasicMaterial color="#00ff00" transparent opacity={0} />
</mesh>

{/* HITBOX FOR 'CONTACT' */}
<mesh 
  position={[7.0, 2.6, 3.4]} 
  onClick={(e) => { e.stopPropagation(); onMenuClick('CONTACT'); }}
  onPointerOver={() => document.body.style.cursor = 'pointer'}
  onPointerOut={() => document.body.style.cursor = 'auto'}
>
  <boxGeometry args={[2.8, 0.8, 1.0]} />
  <meshBasicMaterial transparent opacity={0} />
</mesh>
    </group>
  )
}
useGLTF.preload('/models/scene-transformed.glb')
